MAX_NUM: 2000
BATCH_SIZE: 16
MODE_NAME: "OpenCLIP"
TASK: "itc"
DATA:
  TYPES: ["Attribute/color", "Attribute/action", "Attribute/material", "Attribute/size", "Attribute/state", 
  "Object/location", "Object/size", "Relation/action", "Relation/spatial"]
  TEST_DATA: ["vg"]   
OUTPUT: 
  DIR: "output/our_clip"
  NUM: 5
